version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: debugDivas
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://root:admin@db:5432/debugDivas
    depends_on:
      - db

  parsservise:
    build: ./fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8081
    volumes:
      - ./fastapi:/app
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://root:admin@db:5432/debugDivas
    depends_on:
      - db

volumes:
  postgres_data:
