# Generated by Django 5.1.3 on 2024-11-23 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'локации', 'verbose_name_plural': 'локации'},
        ),
        migrations.AlterModelOptions(
            name='sporttype',
            options={'verbose_name': 'спорт', 'verbose_name_plural': 'спорт'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sport_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sporttype', verbose_name='спорт'),
        ),
    ]
