# Generated by Django 5.1.3 on 2024-11-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sport_type',
            field=models.CharField(max_length=255, null=True, verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Telegram username'),
        ),
    ]
