# Generated by Django 5.1.3 on 2024-11-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_as_followed', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='event',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_as_following', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='users.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_type', to='users.sporttype'),
        ),
    ]
