# Generated by Django 5.1.3 on 2024-11-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='following_user',
        ),
    ]
