# Generated by Django 5.1.3 on 2024-11-23 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_followed_user_and_more'),
        ('users', '0005_alter_customuser_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'мероприятие', 'verbose_name_plural': 'мероприятия'},
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='users.location', verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_type', to='users.sporttype', verbose_name='спорт'),
        ),
    ]
