# Generated by Django 5.1.3 on 2024-11-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_sex_event_gender_alter_event_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255, verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport_type',
            field=models.CharField(max_length=255, verbose_name='вид спорта'),
        ),
    ]
