# Generated by Django 5.1.3 on 2024-11-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_location_alter_event_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.BooleanField(choices=[(None, '...'), (1, 'мужчины'), (2, 'женщины'), (0, 'мужчины, женщины')], verbose_name='пол'),
        ),
    ]
