# Generated by Django 5.1.3 on 2024-11-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.IntegerField(choices=[(None, '...'), (1, 'мужчины'), (2, 'женщины'), (0, 'мужчины, женщины')], verbose_name='пол'),
        ),
    ]
