name: Deploy to VPS

on:
  push:
    branches:
      - master


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ 93.183.83.7 }}
          username: ${{ root }}
          password: ${{ goB,@rBR+DUN3N }}
          # host: ${{ secrets.VPS_IP }}
          # username: ${{ secrets.VPS_USER }}
          # password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e
            PROJECT_DIR="project"
            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR
            if [ ! -d ".git" ]; then
            git clone https://github.com/amerk-dev/DebugDivas.git .
            fi
            
            git pull origin main
            
            # docker compose watch
            docker-compose down
            docker compose up --build -d
            docker ps
